/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "ano-poli": {
    "base": "ano-poli",
    "width": 2448,
    "height": 3264,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "aristotelous": {
    "base": "aristotelous",
    "width": 2151,
    "height": 1378,
    "fallbackWidth": 800,
    "fallbackHeight": 513,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 3840,
    "height": 1524,
    "fallbackWidth": 1920,
    "fallbackHeight": 762,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coastal": {
    "base": "coastal",
    "width": 3840,
    "height": 1524,
    "fallbackWidth": 1920,
    "fallbackHeight": 762,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 3840,
    "height": 2553,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 1920,
    "height": 1279,
    "fallbackWidth": 1920,
    "fallbackHeight": 1279,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "family": {
    "base": "family",
    "width": 2151,
    "height": 1378,
    "fallbackWidth": 800,
    "fallbackHeight": 513,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 2865,
    "height": 3830,
    "fallbackWidth": 800,
    "fallbackHeight": 1069,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food-and-wine": {
    "base": "food-and-wine",
    "width": 2865,
    "height": 3830,
    "fallbackWidth": 800,
    "fallbackHeight": 1069,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "galerius": {
    "base": "galerius",
    "width": 3840,
    "height": 2553,
    "fallbackWidth": 800,
    "fallbackHeight": 532,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero": {
    "base": "hero",
    "width": 1920,
    "height": 2718,
    "fallbackWidth": 1920,
    "fallbackHeight": 2718,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 1920,
    "height": 2718,
    "fallbackWidth": 1920,
    "fallbackHeight": 2718,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "historic": {
    "base": "historic",
    "width": 3840,
    "height": 2553,
    "fallbackWidth": 800,
    "fallbackHeight": 532,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "meteora": {
    "base": "meteora",
    "width": 3840,
    "height": 1524,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "nature": {
    "base": "nature",
    "width": 3840,
    "height": 1524,
    "fallbackWidth": 1920,
    "fallbackHeight": 762,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 2151,
    "height": 1378,
    "fallbackWidth": 1920,
    "fallbackHeight": 1230,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "pella": {
    "base": "pella",
    "width": 2865,
    "height": 3830,
    "fallbackWidth": 800,
    "fallbackHeight": 1069,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 3840,
    "height": 2553,
    "fallbackWidth": 1920,
    "fallbackHeight": 1277,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "private": {
    "base": "private",
    "width": 2865,
    "height": 3830,
    "fallbackWidth": 800,
    "fallbackHeight": 1069,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "rotunda": {
    "base": "rotunda",
    "width": 2448,
    "height": 3264,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "st-demetrios": {
    "base": "st-demetrios",
    "width": 2448,
    "height": 3264,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "vergina": {
    "base": "vergina",
    "width": 2865,
    "height": 3830,
    "fallbackWidth": 800,
    "fallbackHeight": 1069,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "viewpoints": {
    "base": "viewpoints",
    "width": 3840,
    "height": 1524,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "walking": {
    "base": "walking",
    "width": 2448,
    "height": 3264,
    "fallbackWidth": 800,
    "fallbackHeight": 1067,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "waterfront": {
    "base": "waterfront",
    "width": 3840,
    "height": 1524,
    "fallbackWidth": 800,
    "fallbackHeight": 318,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "white-tower": {
    "base": "white-tower",
    "width": 3069,
    "height": 4344,
    "fallbackWidth": 800,
    "fallbackHeight": 1132,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 2865,
    "height": 3830,
    "fallbackWidth": 800,
    "fallbackHeight": 1069,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
